# Generated by Django 3.2.4 on 2021-06-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='User',
            new_name='reciever',
        ),
    ]
