# Generated by Django 3.2.4 on 2021-06-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_rename_user_donations_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='donationoptions',
            field=models.TextField(null=True),
        ),
    ]
