# Generated by Django 3.2.4 on 2021-06-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donations_donationoptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='content',
            new_name='description',
        ),
    ]
